# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadSecureFile@1
      name: nvlicense
      inputs:
        secureFile: 'neuvector-license.txt'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: 'songlongtj/nv_demo'
        tags: |
          $(tag)
    
    - script: |
        docker images
    - task: NeuVectorScan@2
      inputs:
        scanType: 'standalone'
        license: '$(nvlicense. secureFilePath)'
        nvContainerRegistry: 'lsong docker hub'
        nvRepository: 'songlongtj/scanner'
        nvTag: '2.0'
        repository: 'songlongtj/nv_demo'
        tag: '$(Build.BuildId)'
