# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    # steps:
    # - task: NeuVectorScan@2
    #   inputs:
    #     scanType: 'external'
    #     neuvectorScanner: 'nv-gke'
    #     containerRegistry: 'lsong docker hub'
    #     repository: 'songlongtj/alpine'
    #     tag: '3.6'
    - task: DownloadSecureFile@1
      name: nvlicense
      inputs:
        secureFile: 'neuvector-license.txt'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: 'songlongtj/nv_demo'
        tags: |
          $(tag)
    
    - script: |
        docker images
    - task: NeuVectorScan@2
      inputs:
        scanType: 'standalone'
        license: '$(nvlicense.secureFilePath)'
        nvContainerRegistry: 'lsong docker hub'
        nvRepository: 'songlongtj/scanner'
        nvTag: '2.0'
        repository: 'songlongtj/nv_demo'
        tag: '$(Build.BuildId)'
    - script: |
        docker tag songlongtj/nv_demo:$(Build.BuildId) registry.hub.docker.com/songlongtj/nv_demo:$(Build.BuildId)
        docker images
    - task: Docker@2
      displayName: push a scanned image to a registry
      inputs:
        containerRegistry: 'lsong docker hub'
        repository: 'songlongtj/nv_demo'
        command: 'push'
